export const SIGNIN = 'SIGNIN'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'

export const SIGNUP = 'SIGNUP'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const POST_SIGNUP = 'POST_SIGNUP'
export const POST_SIGNUP_SUCCESS = 'POST_SIGNUP_SUCCESS'
export const POST_SIGNUP_FAILURE = 'POST_SIGNUP_FAILURE'

export const CONFIRM_SIGNUP = 'CONFIRM_SIGNUP'
export const CONFIRM_SIGNUP_SUCCESS = 'CONFIRM_SIGNUP_SUCCESS'
export const CONFIRM_SIGNUP_FAILURE = 'CONFIRM_SIGNUP_FAILURE'

export const POST_CONFIRM = 'POST_CONFIRM'
export const POST_CONFIRM_SUCCESS = 'POST_CONFIRM_SUCCESS'
export const POST_CONFIRM_FAILURE = 'POST_CONFIRM_FAILURE'

export const IS_LOGGED_IN = 'IS_LOGGED_IN'
export const IS_LOGGED_IN_SUCCESS = 'IS_LOGGED_IN_SUCCESS'
export const IS_LOGGED_IN_FAILURE = 'IS_LOGGED_IN_FAILURE'

export const GET_USER_BY_ID = 'GET_USER_BY_ID'
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS'
export const GET_USER_BY_ID_FAILURE = 'GET_USER_BY_ID_FAILURE'

export const RESEND_SIGNUP = 'RESEND_SIGNUP'
export const RESEND_SIGNUP_SUCCESS = 'RESEND_SIGNUP_SUCCESS'
export const RESEND_SIGNUP_FAILURE = 'RESEND_SIGNUP_FAILURE'