export const SIGNIN = 'SIGNIN'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'

export const SIGNUP = 'SIGNUP'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE'

export const CONFIRM_NEW_PASSWORD = 'CONFIRM_NEW_PASSWORD'
export const CONFIRM_NEW_PASSWORD_SUCCESS = 'CONFIRM_NEW_PASSWORD_SUCCESS'
export const CONFIRM_NEW_PASSWORD_FAILURE = 'CONFIRM_NEW_PASSWORD_FAILURE'

export const POST_SIGNUP = 'POST_SIGNUP'
export const POST_SIGNUP_SUCCESS = 'POST_SIGNUP_SUCCESS'
export const POST_SIGNUP_FAILURE = 'POST_SIGNUP_FAILURE'

export const POST_SOCIAL_AUTH = 'POST_SOCIAL_AUTH'
export const POST_SOCIAL_AUTH_SUCCESS = 'POST_SOCIAL_AUTH_SUCCESS'
export const POST_SOCIAL_AUTH_FAILURE = 'POST_SOCIAL_AUTH_FAILURE'

export const CONFIRM_SIGNUP = 'CONFIRM_SIGNUP'
export const CONFIRM_SIGNUP_SUCCESS = 'CONFIRM_SIGNUP_SUCCESS'
export const CONFIRM_SIGNUP_FAILURE = 'CONFIRM_SIGNUP_FAILURE'

export const POST_CONFIRM = 'POST_CONFIRM'
export const POST_CONFIRM_SUCCESS = 'POST_CONFIRM_SUCCESS'
export const POST_CONFIRM_FAILURE = 'POST_CONFIRM_FAILURE'

export const IS_LOGGED_IN = 'IS_LOGGED_IN'
export const IS_LOGGED_IN_SUCCESS = 'IS_LOGGED_IN_SUCCESS'
export const IS_LOGGED_IN_FAILURE = 'IS_LOGGED_IN_FAILURE'

export const GET_USER_BY_ID = 'GET_USER_BY_ID'
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS'
export const GET_USER_BY_ID_FAILURE = 'GET_USER_BY_ID_FAILURE'

export const UPLOAD_PROFILE_IMAGE = 'UPLOAD_PROFILE_IMAGE'
export const UPLOAD_PROFILE_IMAGE_SUCCESS = 'UPLOAD_PROFILE_IMAGE_SUCCESS'
export const UPLOAD_PROFILE_IMAGE_FAILURE = 'UPLOAD_PROFILE_IMAGE_FAILURE'

export const RESEND_SIGNUP = 'RESEND_SIGNUP'
export const RESEND_SIGNUP_SUCCESS = 'RESEND_SIGNUP_SUCCESS'
export const RESEND_SIGNUP_FAILURE = 'RESEND_SIGNUP_FAILURE'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

//////////////////// PRODUCT ////////////////////////////
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE'

export const SAVE_PRODUCT = 'SAVE_PRODUCT'
export const SAVE_PRODUCT_SUCCESS = 'SAVE_PRODUCT_SUCCESS'
export const SAVE_PRODUCT_FAILURE = 'SAVE_PRODUCT_FAILURE'

export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE'

export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID'
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS'
export const GET_PRODUCT_BY_ID_FAILURE = 'GET_PRODUCT_BY_ID_FAILURE'

export const REVERSE_GEOCODING = 'REVERSE_GEOCODING'
export const REVERSE_GEOCODING_SUCCESS = 'REVERSE_GEOCODING_SUCCESS'
export const REVERSE_GEOCODING_FAILURE = 'REVERSE_GEOCODING_FAILURE'

export const LIKE_DISLIKE_PRODUCT = 'LIKE_DISLIKE_PRODUCT'
export const LIKE_DISLIKE_PRODUCT_SUCCESS = 'LIKE_DISLIKE_PRODUCT_SUCCESS'
export const LIKE_DISLIKE_PRODUCT_FAILURE = 'LIKE_DISLIKE_PRODUCT_FAILURE'

export const DO_COMMENT_ON_PRODUCT = 'DO_COMMENT_ON_PRODUCT'
export const DO_COMMENT_ON_PRODUCT_SUCCESS = 'DO_COMMENT_ON_PRODUCT_SUCCESS'
export const DO_COMMENT_ON_PRODUCT_FAILURE = 'DO_COMMENT_ON_PRODUCT_FAILURE'

export const SEARCH = 'SEARCH'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAILURE = 'SEARCH_FAILURE'

export const SEND_FEEDBACK = 'SEND_FEEDBACK'
export const SEND_FEEDBACK_SUCCESS = 'SEND_FEEDBACK_SUCCESS'
export const SEND_FEEDBACK_FAILURE = 'SEND_FEEDBACK_FAILURE'

export const ACTION_ON_COMMENT = 'ACTION_ON_COMMENT'
export const ACTION_ON_COMMENT_SUCCESS = 'ACTION_ON_COMMENT_SUCCESS'
export const ACTION_ON_COMMENT_FAILURE = 'ACTION_ON_COMMENT_FAILURE'